name: Deploy Stg / Dev Dashboard

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  SLACK_CHANNEL: "C09CHP3SBHA"

jobs:
  notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Initiate the deployment launch sequence
        id: launch_sequence
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL }}
            text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: "Section kedua"
      - name: Countdown until launch
        run: sleep 10
      - name: Update the original message with success
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL }}
            ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: "Deployment finished! :rocket:"
            attachments:
              - color: "28a745"
                fields:
                  - title: "Status"
                    short: true
                    value: "Completed"
