name: Deploy Stg / Dev Dashboard

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  SLACK_CHANNEL: "C09CHP3SBHA"
  TEXT: "text inside variable"

jobs:
  notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Initiate the deployment launch sequence
        id: launch_sequence
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL }}
            text: "Deployment started :eyes:"
            attachments:
              - color: "#dbab09"
                fields:
                  - title: "Status"
                    short: true
                    value: "In Progress"
                  - title: "Duration"
                    short: true
                    value: "0 seconds"
                footer: "Deployment initiated"
      - name: Countdown until launch
        run: sleep 5
      - name: Update first
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL }}
            ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: if [[ -n "${{ env.TEXT }}" ]]; then echo "${{ env.TEXT }}"; fi
            attachments:
              - color: "#aa17a8ff"
                fields:
                  - title: "Status"
                    short: true
                    value: "Working"
                  - title: "Duration"
                    short: true
                    value: "5 seconds"
      - name: Countdown until launch
        run: sleep 5
      - name: Update the original message with success
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL }}
            ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: "${{ env.TEXT == 'text' && env.TEXT || 'Deployment finished :rocket:' }}"
            attachments:
              - color: "#66FF00"
                fields:
                  - title: "Status"
                    short: true
                    value: "Completed"
                  - title: "Duration"
                    short: true
                    value: "10 seconds"
